version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./files/hiveddls:/docker-entrypoint-initdb.d
      - ./files/share/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    environment:
      MYSQL_DATABASE: metastore
      MYSQL_ROOT_PASSWORD: root
    container_name: db_mysql
    networks:
      - app-net
  workspace:
    build: ./files
    command: sleep infinity
    volumes:
      - ./storageLayer/:/home/pyspark/storageLayer/
    depends_on:
      - mysql
    container_name: pyspark
    networks:
      - app-net
  kafka:
    build: ./files/kafka
    command: sh /etc/rc.local/start_up.sh
    container_name: kafka
    networks:
      - app-net
  nodejs:
    build: ./files/nodejs
    command: node /usr/src/app/express.js
    container_name: nodejs
    networks:
      - app-net
  metabase:
    image: metabase/metabase:v0.42.3
    env_file: ./env
    volumes:
      - ./data/metabase-data:/metabase-data
    ports:
      - 3000:3000
    depends_on:
      - postgres-mb
    networks:
      - app-net
    container_name: metabase_bi
  postgres-mb:
    image: postgres:13.6-bullseye
    env_file: ./env
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-net
    container_name: metabase_postgres

networks:
  app-net:
    driver: bridge